language: node_js
node_js: 12.6
cache: yarn
install:
  - npm i yarn@1.17.3 -g
  - yarn config set cache-folder $HOME/.yarn-cache
  - yarn

before_script:
  - yarn build-ts

script:
  - yarn check-style
  - yarn check-lint
  - yarn check-unit

notifications:
  email:
    on_success: change
    on_failure: change
